version: "3"
services:
  seatsurfing-server:
    image: seatsurfing/backend
    container_name: seatsurfing-server
    hostname: seatsurfing-server
    restart: unless-stopped
    environment:
      POSTGRES_URL: 'postgres://postgres:postgres@seatsurfing-db/seatsurfing?sslmode=disable'
      JWT_SIGNING_KEY: ${JWT_SIGNING_KEY}
      BOOKING_UI_BACKEND: 'seatsurfing-booking-ui:3001'
      ADMIN_UI_BACKEND: 'seatsurfing-admin-ui:3000'
      PUBLIC_URL: 'https://booking.shantaram-spb.ru'
      FRONTEND_URL: 'https://booking.shantaram-spb.ru'
  seatsurfing-booking-ui:
    image: seatsurfing/booking-ui
    container_name: seatsurfing-booking-ui
    hostname: seatsurfing-booking-ui
    restart: unless-stopped
    environment:
      FRONTEND_URL: 'https://booking.shantaram-spb.ru'
  seatsurfing-admin-ui:
    image: seatsurfing/admin-ui
    container_name: seatsurfing-admin-ui
    hostname: seatsurfing-admin-ui
    restart: unless-stopped
    environment:
      FRONTEND_URL: 'https://booking.shantaram-spb.ru'
  seatsurfing-db:
    image: postgres:12
    container_name: seatsurfing-db
    hostname: seatsurfing-db
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: seatsurfing

networks:
  default:
    external:
      name: shantaram-network